// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equities.sql

package db

import (
	"context"
)

const getEquityByConid = `-- name: GetEquityByConid :one
SELECT conid, ticker, name, exchange
FROM equities
WHERE conid = $1
`

func (q *Queries) GetEquityByConid(ctx context.Context, conid int32) (Equity, error) {
	row := q.db.QueryRow(ctx, getEquityByConid, conid)
	var i Equity
	err := row.Scan(
		&i.Conid,
		&i.Ticker,
		&i.Name,
		&i.Exchange,
	)
	return i, err
}

const insertEquity = `-- name: InsertEquity :exec
INSERT INTO equities (conid, ticker, name, exchange)
VALUES ($1, $2, $3, $4)
`

type InsertEquityParams struct {
	Conid    int32
	Ticker   string
	Name     string
	Exchange string
}

func (q *Queries) InsertEquity(ctx context.Context, arg InsertEquityParams) error {
	_, err := q.db.Exec(ctx, insertEquity,
		arg.Conid,
		arg.Ticker,
		arg.Name,
		arg.Exchange,
	)
	return err
}

const listEquities = `-- name: ListEquities :many
SELECT conid, ticker, name, exchange
FROM equities
ORDER BY ticker
`

func (q *Queries) ListEquities(ctx context.Context) ([]Equity, error) {
	rows, err := q.db.Query(ctx, listEquities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equity
	for rows.Next() {
		var i Equity
		if err := rows.Scan(
			&i.Conid,
			&i.Ticker,
			&i.Name,
			&i.Exchange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
