// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EquityUniverse struct {
	Conid           int32
	Ticker          string
	Exchange        string
	PeRatio         pgtype.Float8
	PriceToSales    pgtype.Float8
	ReturnOnEquity  pgtype.Float8
	BusinessSummary pgtype.Text
	UpdatedAt       pgtype.Timestamp
}
